"""create initial tables

Revision ID: 8966c628c017
Revises: 
Create Date: 2026-07-10 17:58:39.864693
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8966c628c017'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenues',
    sa.Column('revenue_no', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('revenue_date', sa.Date(), nullable=False),
    sa.Column('related_order_no', sa.String(length=100), nullable=True),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenues_customer'), 'revenues', ['customer'], unique=False)
    op.create_index(op.f('ix_revenues_received'), 'revenues', ['received'], unique=False)
    op.create_index(op.f('ix_revenues_related_order_no'), 'revenues', ['related_order_no'], unique=False)
    op.create_index(op.f('ix_revenues_revenue_date'), 'revenues', ['revenue_date'], unique=False)
    op.create_index(op.f('ix_revenues_revenue_no'), 'revenues', ['revenue_no'], unique=True)
    op.create_index(op.f('ix_revenues_source'), 'revenues', ['source'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('purchase_url', sa.Text(), nullable=True),
    sa.Column('login_url', sa.Text(), nullable=True),
    sa.Column('login_account', sa.Text(), nullable=True),
    sa.Column('login_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('country_region', sa.String(length=100), nullable=True),
    sa.Column('continue_cooperation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('manual_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_index(op.f('ix_suppliers_type'), 'suppliers', ['type'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cost_items',
    sa.Column('cost_no', sa.String(length=100), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('include_all_cost', sa.Boolean(), nullable=False),
    sa.Column('include_real_cost', sa.Boolean(), nullable=False),
    sa.Column('one_time', sa.Boolean(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_period', sa.String(length=20), nullable=True),
    sa.Column('period_started_at', sa.Date(), nullable=True),
    sa.Column('period_finished_at', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_items_cost_date'), 'cost_items', ['cost_date'], unique=False)
    op.create_index(op.f('ix_cost_items_cost_no'), 'cost_items', ['cost_no'], unique=True)
    op.create_index(op.f('ix_cost_items_cost_type'), 'cost_items', ['cost_type'], unique=False)
    op.create_index(op.f('ix_cost_items_include_all_cost'), 'cost_items', ['include_all_cost'], unique=False)
    op.create_index(op.f('ix_cost_items_include_real_cost'), 'cost_items', ['include_real_cost'], unique=False)
    op.create_index(op.f('ix_cost_items_source_id'), 'cost_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_cost_items_source_type'), 'cost_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_cost_items_supplier_id'), 'cost_items', ['supplier_id'], unique=False)
    op.create_table('files',
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('purchase_no', sa.String(length=100), nullable=False),
    sa.Column('purchase_type', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=False),
    sa.Column('purchaser_id', sa.UUID(), nullable=True),
    sa.Column('order_url', sa.Text(), nullable=True),
    sa.Column('voucher_file_id', sa.UUID(), nullable=True),
    sa.Column('include_all_cost', sa.Boolean(), nullable=False),
    sa.Column('include_real_cost', sa.Boolean(), nullable=False),
    sa.Column('cost_status', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchaser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['voucher_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_cost_status'), 'purchases', ['cost_status'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_no'), 'purchases', ['purchase_no'], unique=True)
    op.create_index(op.f('ix_purchases_purchase_type'), 'purchases', ['purchase_type'], unique=False)
    op.create_index(op.f('ix_purchases_purchased_at'), 'purchases', ['purchased_at'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_table('accounts',
    sa.Column('account_no', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('login_url', sa.Text(), nullable=True),
    sa.Column('login_account', sa.Text(), nullable=True),
    sa.Column('login_password_encrypted', sa.Text(), nullable=True),
    sa.Column('bind_email', sa.String(length=200), nullable=True),
    sa.Column('recovery_email', sa.String(length=200), nullable=True),
    sa.Column('country_region', sa.String(length=100), nullable=True),
    sa.Column('proxy_requirement', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('participate_operation', sa.Boolean(), nullable=False),
    sa.Column('include_real_cost', sa.Boolean(), nullable=False),
    sa.Column('cost_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('available_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_days', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_no'), 'accounts', ['account_no'], unique=True)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_purchase_id'), 'accounts', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_supplier_id'), 'accounts', ['supplier_id'], unique=False)
    op.create_table('evaluation_batches',
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('purchase_quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_total_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('test_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_pass_count', sa.Integer(), nullable=False),
    sa.Column('day7_available_count', sa.Integer(), nullable=False),
    sa.Column('day30_available_count', sa.Integer(), nullable=False),
    sa.Column('banned_count', sa.Integer(), nullable=False),
    sa.Column('refund_count', sa.Integer(), nullable=False),
    sa.Column('effective_account_count', sa.Integer(), nullable=False),
    sa.Column('nominal_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('real_effective_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conclusion', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_batches_account_type'), 'evaluation_batches', ['account_type'], unique=False)
    op.create_index(op.f('ix_evaluation_batches_batch_no'), 'evaluation_batches', ['batch_no'], unique=True)
    op.create_index(op.f('ix_evaluation_batches_conclusion'), 'evaluation_batches', ['conclusion'], unique=False)
    op.create_index(op.f('ix_evaluation_batches_purchase_id'), 'evaluation_batches', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_evaluation_batches_supplier_id'), 'evaluation_batches', ['supplier_id'], unique=False)
    op.create_table('proxy_pools',
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('proxy_type', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('quantity_or_traffic', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('suitable_for_login', sa.Boolean(), nullable=False),
    sa.Column('suitable_for_api', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('continue_purchase', sa.Boolean(), nullable=False),
    sa.Column('include_real_cost', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_pools_proxy_type'), 'proxy_pools', ['proxy_type'], unique=False)
    op.create_index(op.f('ix_proxy_pools_purchase_id'), 'proxy_pools', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_proxy_pools_status'), 'proxy_pools', ['status'], unique=False)
    op.create_index(op.f('ix_proxy_pools_supplier_id'), 'proxy_pools', ['supplier_id'], unique=False)
    op.create_table('servers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('login_host', sa.String(length=200), nullable=True),
    sa.Column('ssh_username', sa.String(length=100), nullable=True),
    sa.Column('ssh_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('console_url', sa.Text(), nullable=True),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('memory', sa.String(length=100), nullable=True),
    sa.Column('disk', sa.String(length=100), nullable=True),
    sa.Column('bandwidth', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('include_real_cost', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=False)
    op.create_index(op.f('ix_servers_purchase_id'), 'servers', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_servers_status'), 'servers', ['status'], unique=False)
    op.create_index(op.f('ix_servers_supplier_id'), 'servers', ['supplier_id'], unique=False)
    op.create_table('account_evaluations',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('can_login', sa.Boolean(), nullable=True),
    sa.Column('has_risk_control', sa.Boolean(), nullable=True),
    sa.Column('target_model_available', sa.Boolean(), nullable=True),
    sa.Column('need_fixed_proxy', sa.Boolean(), nullable=True),
    sa.Column('request_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_response_quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('available_days', sa.Integer(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_refunded', sa.Boolean(), nullable=False),
    sa.Column('manual_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conclusion', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['evaluation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_evaluations_account_id'), 'account_evaluations', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_evaluations_batch_id'), 'account_evaluations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_account_evaluations_conclusion'), 'account_evaluations', ['conclusion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_evaluations_conclusion'), table_name='account_evaluations')
    op.drop_index(op.f('ix_account_evaluations_batch_id'), table_name='account_evaluations')
    op.drop_index(op.f('ix_account_evaluations_account_id'), table_name='account_evaluations')
    op.drop_table('account_evaluations')
    op.drop_index(op.f('ix_servers_supplier_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_status'), table_name='servers')
    op.drop_index(op.f('ix_servers_purchase_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_proxy_pools_supplier_id'), table_name='proxy_pools')
    op.drop_index(op.f('ix_proxy_pools_status'), table_name='proxy_pools')
    op.drop_index(op.f('ix_proxy_pools_purchase_id'), table_name='proxy_pools')
    op.drop_index(op.f('ix_proxy_pools_proxy_type'), table_name='proxy_pools')
    op.drop_table('proxy_pools')
    op.drop_index(op.f('ix_evaluation_batches_supplier_id'), table_name='evaluation_batches')
    op.drop_index(op.f('ix_evaluation_batches_purchase_id'), table_name='evaluation_batches')
    op.drop_index(op.f('ix_evaluation_batches_conclusion'), table_name='evaluation_batches')
    op.drop_index(op.f('ix_evaluation_batches_batch_no'), table_name='evaluation_batches')
    op.drop_index(op.f('ix_evaluation_batches_account_type'), table_name='evaluation_batches')
    op.drop_table('evaluation_batches')
    op.drop_index(op.f('ix_accounts_supplier_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_purchase_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_no'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchased_at'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchase_type'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchase_no'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_cost_status'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('files')
    op.drop_index(op.f('ix_cost_items_supplier_id'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_source_type'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_source_id'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_include_real_cost'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_include_all_cost'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_cost_type'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_cost_no'), table_name='cost_items')
    op.drop_index(op.f('ix_cost_items_cost_date'), table_name='cost_items')
    op.drop_table('cost_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_type'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_revenues_source'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_revenue_no'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_revenue_date'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_related_order_no'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_received'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_customer'), table_name='revenues')
    op.drop_table('revenues')
    # ### end Alembic commands ###

